/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "dff.v:1" *)
module dff(C, R, D, Q);
  (* src = "dff.v:8|all2nand.v:18" *)
  wire _00_;
  (* src = "dff.v:8|all2nand.v:17" *)
  wire _01_;
  (* src = "dff.v:8|all2nand.v:19" *)
  wire _02_;
  (* src = "dff.v:8|all2nand.v:20" *)
  wire _03_;
  (* src = "dff.v:8|all2nand.v:21" *)
  wire _04_;
  (* src = "dff.v:8|all2nand.v:24" *)
  wire _05_;
  (* src = "dff.v:8|all2nand.v:22" *)
  wire _06_;
  (* src = "dff.v:8|all2nand.v:23" *)
  wire _07_;
  (* src = "dff.v:8|all2nand.v:15" *)
  wire _08_;
  (* src = "dff.v:2" *)
  input C;
  (* src = "dff.v:4" *)
  input D;
  (* src = "dff.v:5" *)
  output Q;
  (* src = "dff.v:3" *)
  input R;
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:26|all2nand.v:3" *)
  NAND _09_ (
    .A(R),
    .B(R),
    .Y(_08_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:27" *)
  NAND _10_ (
    .A(_08_),
    .B(C),
    .Y(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:28" *)
  NAND _11_ (
    .A(D),
    .B(_06_),
    .Y(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:29" *)
  NAND _12_ (
    .A(_01_),
    .B(_07_),
    .Y(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:30" *)
  NAND _13_ (
    .A(_02_),
    .B(_08_),
    .Y(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:31" *)
  NAND _14_ (
    .A(_03_),
    .B(_03_),
    .Y(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:32" *)
  NAND _15_ (
    .A(_03_),
    .B(_00_),
    .Y(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:33" *)
  NAND _16_ (
    .A(_04_),
    .B(_00_),
    .Y(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:34" *)
  NAND _17_ (
    .A(_06_),
    .B(Q),
    .Y(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dff.v:8|all2nand.v:35" *)
  NAND _18_ (
    .A(_07_),
    .B(_05_),
    .Y(Q)
  );
endmodule
