/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "counter.v:1" *)
module counter(clk, rst, count);
  (* src = "counter.v:7" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  (* src = "counter.v:7|all2nand.v:18" *)
  wire _014_;
  (* src = "counter.v:7|all2nand.v:17" *)
  wire _015_;
  (* src = "counter.v:7|all2nand.v:19" *)
  wire _016_;
  (* src = "counter.v:7|all2nand.v:20" *)
  wire _017_;
  (* src = "counter.v:7|all2nand.v:21" *)
  wire _018_;
  (* src = "counter.v:7|all2nand.v:24" *)
  wire _019_;
  (* src = "counter.v:7|all2nand.v:22" *)
  wire _020_;
  (* src = "counter.v:7|all2nand.v:23" *)
  wire _021_;
  (* src = "counter.v:7|all2nand.v:15" *)
  wire _022_;
  (* src = "counter.v:7|all2nand.v:18" *)
  wire _023_;
  (* src = "counter.v:7|all2nand.v:17" *)
  wire _024_;
  (* src = "counter.v:7|all2nand.v:19" *)
  wire _025_;
  (* src = "counter.v:7|all2nand.v:20" *)
  wire _026_;
  (* src = "counter.v:7|all2nand.v:21" *)
  wire _027_;
  (* src = "counter.v:7|all2nand.v:24" *)
  wire _028_;
  (* src = "counter.v:7|all2nand.v:22" *)
  wire _029_;
  (* src = "counter.v:7|all2nand.v:23" *)
  wire _030_;
  (* src = "counter.v:7|all2nand.v:15" *)
  wire _031_;
  (* src = "counter.v:7|all2nand.v:18" *)
  wire _032_;
  (* src = "counter.v:7|all2nand.v:17" *)
  wire _033_;
  (* src = "counter.v:7|all2nand.v:19" *)
  wire _034_;
  (* src = "counter.v:7|all2nand.v:20" *)
  wire _035_;
  (* src = "counter.v:7|all2nand.v:21" *)
  wire _036_;
  (* src = "counter.v:7|all2nand.v:24" *)
  wire _037_;
  (* src = "counter.v:7|all2nand.v:22" *)
  wire _038_;
  (* src = "counter.v:7|all2nand.v:23" *)
  wire _039_;
  (* src = "counter.v:7|all2nand.v:15" *)
  wire _040_;
  (* src = "counter.v:7|all2nand.v:18" *)
  wire _041_;
  (* src = "counter.v:7|all2nand.v:17" *)
  wire _042_;
  (* src = "counter.v:7|all2nand.v:19" *)
  wire _043_;
  (* src = "counter.v:7|all2nand.v:20" *)
  wire _044_;
  (* src = "counter.v:7|all2nand.v:21" *)
  wire _045_;
  (* src = "counter.v:7|all2nand.v:24" *)
  wire _046_;
  (* src = "counter.v:7|all2nand.v:22" *)
  wire _047_;
  (* src = "counter.v:7|all2nand.v:23" *)
  wire _048_;
  (* src = "counter.v:7|all2nand.v:15" *)
  wire _049_;
  (* src = "counter.v:2" *)
  input clk;
  (* src = "counter.v:4" *)
  output [3:0] count;
  (* src = "counter.v:3" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _050_ (
    .A(count[1]),
    .B(count[1]),
    .Y(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _051_ (
    .A(count[0]),
    .B(count[0]),
    .Y(_000_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _052_ (
    .A(count[2]),
    .B(count[2]),
    .Y(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _053_ (
    .A(count[3]),
    .B(count[3]),
    .Y(_002_)
  );
  NAND _054_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _055_ (
    .A(_003_),
    .B(_003_),
    .Y(_004_)
  );
  NAND _056_ (
    .A(_013_),
    .B(_000_[0]),
    .Y(_005_)
  );
  NAND _057_ (
    .A(_003_),
    .B(_005_),
    .Y(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _058_ (
    .A(_006_),
    .B(_006_),
    .Y(_000_[1])
  );
  NAND _059_ (
    .A(count[2]),
    .B(_004_),
    .Y(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _060_ (
    .A(_007_),
    .B(_007_),
    .Y(_008_)
  );
  NAND _061_ (
    .A(_001_),
    .B(_003_),
    .Y(_009_)
  );
  NAND _062_ (
    .A(_007_),
    .B(_009_),
    .Y(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _063_ (
    .A(_010_),
    .B(_010_),
    .Y(_000_[2])
  );
  NAND _064_ (
    .A(count[3]),
    .B(_007_),
    .Y(_011_)
  );
  NAND _065_ (
    .A(_002_),
    .B(_008_),
    .Y(_012_)
  );
  NAND _066_ (
    .A(_011_),
    .B(_012_),
    .Y(_000_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:26|all2nand.v:3" *)
  NAND _067_ (
    .A(rst),
    .B(rst),
    .Y(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:27" *)
  NAND _068_ (
    .A(_022_),
    .B(clk),
    .Y(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:28" *)
  NAND _069_ (
    .A(_000_[0]),
    .B(_020_),
    .Y(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:29" *)
  NAND _070_ (
    .A(_015_),
    .B(_021_),
    .Y(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:30" *)
  NAND _071_ (
    .A(_016_),
    .B(_022_),
    .Y(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:31" *)
  NAND _072_ (
    .A(_017_),
    .B(_017_),
    .Y(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:32" *)
  NAND _073_ (
    .A(_017_),
    .B(_014_),
    .Y(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:33" *)
  NAND _074_ (
    .A(_018_),
    .B(_014_),
    .Y(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:34" *)
  NAND _075_ (
    .A(_020_),
    .B(count[0]),
    .Y(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:35" *)
  NAND _076_ (
    .A(_021_),
    .B(_019_),
    .Y(count[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:26|all2nand.v:3" *)
  NAND _077_ (
    .A(rst),
    .B(rst),
    .Y(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:27" *)
  NAND _078_ (
    .A(_031_),
    .B(clk),
    .Y(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:28" *)
  NAND _079_ (
    .A(_000_[1]),
    .B(_029_),
    .Y(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:29" *)
  NAND _080_ (
    .A(_024_),
    .B(_030_),
    .Y(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:30" *)
  NAND _081_ (
    .A(_025_),
    .B(_031_),
    .Y(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:31" *)
  NAND _082_ (
    .A(_026_),
    .B(_026_),
    .Y(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:32" *)
  NAND _083_ (
    .A(_026_),
    .B(_023_),
    .Y(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:33" *)
  NAND _084_ (
    .A(_027_),
    .B(_023_),
    .Y(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:34" *)
  NAND _085_ (
    .A(_029_),
    .B(count[1]),
    .Y(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:35" *)
  NAND _086_ (
    .A(_030_),
    .B(_028_),
    .Y(count[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:26|all2nand.v:3" *)
  NAND _087_ (
    .A(rst),
    .B(rst),
    .Y(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:27" *)
  NAND _088_ (
    .A(_040_),
    .B(clk),
    .Y(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:28" *)
  NAND _089_ (
    .A(_000_[2]),
    .B(_038_),
    .Y(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:29" *)
  NAND _090_ (
    .A(_033_),
    .B(_039_),
    .Y(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:30" *)
  NAND _091_ (
    .A(_034_),
    .B(_040_),
    .Y(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:31" *)
  NAND _092_ (
    .A(_035_),
    .B(_035_),
    .Y(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:32" *)
  NAND _093_ (
    .A(_035_),
    .B(_032_),
    .Y(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:33" *)
  NAND _094_ (
    .A(_036_),
    .B(_032_),
    .Y(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:34" *)
  NAND _095_ (
    .A(_038_),
    .B(count[2]),
    .Y(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:35" *)
  NAND _096_ (
    .A(_039_),
    .B(_037_),
    .Y(count[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:26|all2nand.v:3" *)
  NAND _097_ (
    .A(rst),
    .B(rst),
    .Y(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:27" *)
  NAND _098_ (
    .A(_049_),
    .B(clk),
    .Y(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:28" *)
  NAND _099_ (
    .A(_000_[3]),
    .B(_047_),
    .Y(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:29" *)
  NAND _100_ (
    .A(_042_),
    .B(_048_),
    .Y(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:30" *)
  NAND _101_ (
    .A(_043_),
    .B(_049_),
    .Y(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:31" *)
  NAND _102_ (
    .A(_044_),
    .B(_044_),
    .Y(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:32" *)
  NAND _103_ (
    .A(_044_),
    .B(_041_),
    .Y(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:33" *)
  NAND _104_ (
    .A(_045_),
    .B(_041_),
    .Y(_048_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:34" *)
  NAND _105_ (
    .A(_047_),
    .B(count[3]),
    .Y(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter.v:7|all2nand.v:35" *)
  NAND _106_ (
    .A(_048_),
    .B(_046_),
    .Y(count[3])
  );
endmodule
