/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "counter1bit.v:1" *)
module counter1bit(clk, rst, count);
  (* src = "counter1bit.v:7" *)
  wire _00_;
  (* src = "counter1bit.v:7|all2nand.v:18" *)
  wire _01_;
  (* src = "counter1bit.v:7|all2nand.v:17" *)
  wire _02_;
  (* src = "counter1bit.v:7|all2nand.v:19" *)
  wire _03_;
  (* src = "counter1bit.v:7|all2nand.v:20" *)
  wire _04_;
  (* src = "counter1bit.v:7|all2nand.v:21" *)
  wire _05_;
  (* src = "counter1bit.v:7|all2nand.v:24" *)
  wire _06_;
  (* src = "counter1bit.v:7|all2nand.v:22" *)
  wire _07_;
  (* src = "counter1bit.v:7|all2nand.v:23" *)
  wire _08_;
  (* src = "counter1bit.v:7|all2nand.v:15" *)
  wire _09_;
  (* src = "counter1bit.v:2" *)
  input clk;
  (* src = "counter1bit.v:4" *)
  output count;
  (* src = "counter1bit.v:3" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "all2nand.v:3" *)
  NAND _10_ (
    .A(count),
    .B(count),
    .Y(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:26|all2nand.v:3" *)
  NAND _11_ (
    .A(rst),
    .B(rst),
    .Y(_09_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:27" *)
  NAND _12_ (
    .A(_09_),
    .B(clk),
    .Y(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:28" *)
  NAND _13_ (
    .A(_00_),
    .B(_07_),
    .Y(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:29" *)
  NAND _14_ (
    .A(_02_),
    .B(_08_),
    .Y(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:30" *)
  NAND _15_ (
    .A(_03_),
    .B(_09_),
    .Y(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:31" *)
  NAND _16_ (
    .A(_04_),
    .B(_04_),
    .Y(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:32" *)
  NAND _17_ (
    .A(_04_),
    .B(_01_),
    .Y(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:33" *)
  NAND _18_ (
    .A(_05_),
    .B(_01_),
    .Y(_08_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:34" *)
  NAND _19_ (
    .A(_07_),
    .B(count),
    .Y(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter1bit.v:7|all2nand.v:35" *)
  NAND _20_ (
    .A(_08_),
    .B(_06_),
    .Y(count)
  );
endmodule
